packages:
  - codex-cli
  - codex-rs/responses-api-proxy/npm
  - sdk/typescript

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080
minimumReleaseAgeExclude: []

blockExoticSubdeps: true
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
trustPolicyExclude: []
allowBuilds: {}
